### ISSUE TITLE
arpy: command not found

### ISSUE THREAD

**Issue by KittenYang** [ivanvza/arpy#15]
<img width="222" alt="2017-02-23 04 38 23" src="https://cloud.githubusercontent.com/assets/5517281/23231219/ff177ae2-f981-11e6-8e1d-877a0a4b7336.png">
 All steps are OK,but command not found.Do you have any idea?

**Comment by ivanvza** [comment]
Hi @KittenYang, have you tried running arpy.py from the directory you cloned it into?
