### ISSUE TITLE
Can't find arpy on path after make install

### ISSUE THREAD

**Issue by wildeyes** [ivanvza/arpy#6]
Running El Capitan.

**Comment by ivanvza** [comment]
Hey @wildeyes, I assume you are reffering to the install make & make install of [libdnet](https://github.com/ivanvza/arpy#libdnet)? This is only one of the requirements required to run arpy.

Arpy will not be in your env path, unless you go add it.

What happens after you run it from the directory you git cloned it to?

**Comment by ivanvza** [comment]
@wildeyes, this is being closed as no response is given.
Please let me know if there is anything else 😄.
